[package]
name = "type_extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo_metadata = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full"] }
walkdir = { workspace = true }
